# Study Criteria, Dev Environment, EH Download, and Database Setup

Repo: `ewnike/NHL-Beyond-27` — *MADS Milestone I Project*
Python: 3.13.7 (pyenv env: `nhl_beyond27-3.13.7`)
Editors/Tools: VSCode, Git/GitHub, Postgres + pgAdmin
Logs: via `log_utils.py` (default `logs/`)

**This notebook covers**
1) Study criteria
2) Dev environment (VS Code, Git, Postgres/pgAdmin)
3) Evolving-Hockey export (where/how to place CSV)
4) (Optional) S3 pull of cached inputs
5) Run pipeline CLIs (build, finalize, load DB)
6) Quick verification (tables + sanity checks)

## Study criteria
- Window: five consecutive seasons per player, `rel_age ∈ {-2,-1,0,1,2}` (peak = `0`)
- Strength: EV/5v5 only
- Minutes threshold: **EV TOI ≥ 500 per season** within the 5-year window
- Seasons: 2013–14 → 2024–25
- Positions: `D` = defense; all others treated as forwards
- **Normalization:** compute **within-player** z-scores over the 5-year window for CF%, CF/60, CA/60

## Order of Operations
- `ingest_peak_season.py` → loads EH peak export → `public.player_peak_season`
- `build_player_streaks_and_aligned.py` → `public.player_five_year_aligned`
- `build_player_five_year_aligned_z.py` → `public.player_five_year_aligned_z`
- `CREATE VIEW` → `public.v_player_spicy_by_rel_age`

## Metrics (used later)
- **SPICY (equal-weight):** `( z(CF%) + z(CF/60) − z(CA/60) ) / 3`
- **Role-weighted SPICY (primary):**
  - Forwards: `0.5·z(CF%) + 0.3·z(CF/60) − 0.2·z(CA/60)`
  - Defense:  `0.3·z(CF%) + 0.2·z(CF/60) − 0.5·z(CA/60)`
- **Curvature vs peak:** `Δz_t = z_t − z_{t=0}`
- **Peak Δ (headline delta):** `z_{t=0} − mean(z_{t∈{-2,-1,0,1,2}})` (or exclude peak for a 4-season baseline)

**Downstream outputs**
- `player_five_year_aligned` (source, aligned seasons)
- `player_five_year_aligned_z` (within-player z-scores + SPICY + curvature/Peak Δ)

# Project dirs & environment (narrative)

- We keep the project reproducible and portable by pinning the environment and fixing a predictable directory layout.
- Environment. Python 3.13.7 (pyenv: nhl_beyond27-3.13.7) with a requirements lock; secrets stay out of Git via a local .env.
- Data layout. All inputs under data/, all generated artifacts under data/outputs/, logs in logs/. This isolates heavyweight/derived files so the repo stays light and rebuilds are deterministic.
- Configuration. Runtime settings (e.g., DB connection) come from environment variables; notebooks never hard-code credentials.

** Why it matters. New machines (or graders) can clone → create env → drop raw CSVs into data/ → run the same commands and get the same tables/plots.**

In [57]:
# Project dirs & environment
import os
import sys
from pathlib import Path

import pandas as pd

# --- Directories ---
ROOT = Path.cwd()
DATA = ROOT / "data"
OUT  = DATA / "outputs"
LOGS = ROOT / "logs"
for d in (DATA, OUT, LOGS):
    d.mkdir(parents=True, exist_ok=True)


# --- .env (optional, never committed) ---
# --- .env (optional, never committed) ---
try:
    # Silence python-dotenv's parser chatter
    import logging
    logging.getLogger("dotenv.main").setLevel(logging.ERROR)

    from pathlib import Path

    from dotenv import dotenv_values, find_dotenv, load_dotenv

    ENV_PATH = find_dotenv(usecwd=True)
    if ENV_PATH and Path(ENV_PATH).is_file():
        # (Optional) quick parse to catch truly broken first lines without printing warnings
        _ = dotenv_values(ENV_PATH)  # returns dict; raises on severe I/O only
        load_dotenv(ENV_PATH)        # quietly loads vars into os.environ
        print("Loaded .env from:", ENV_PATH)
    else:
        print(".env not found (skipping)")
except ImportError:
    # python-dotenv not installed — totally fine
    pass


# --- Quick environment report ---
print("Working dir :", ROOT)
print("Outputs dir :", OUT.resolve())
print("Python      :", sys.version.split()[0])
print("Pandas      :", pd.__version__)
print("PYENV_ENV   :", os.getenv("PYENV_VERSION", "(unset)"))

# Common env vars (safe to print existence, not values)
for key in ["DATABASE_URL", "PGHOST", "PGDATABASE", "PGUSER", "PGPORT"]:
    print(f"{key:12}: {'set' if os.getenv(key) else 'unset'}")

# --- Writeability sanity check ---
try:
    probe = OUT / ".write_probe"
    probe.write_text("ok", encoding="utf-8")
    probe.unlink(missing_ok=True)
    print("Write test  :", "OK")
except Exception as e:
    print("Write test  :", f"FAILED → {e}")

# Optional: show a minimal tree (without walking big dirs)
print("\nProject layout (key paths):")
print(f"  {ROOT.name}/")
print("   ├─ data/")
print("   │   └─ outputs/")
print("   └─ logs/")

Loaded .env from: /Users/ericwiniecke/Documents/github/NHL-Beyond-27/.env
Working dir : /Users/ericwiniecke/Documents/github/NHL-Beyond-27
Outputs dir : /Users/ericwiniecke/Documents/github/NHL-Beyond-27/data/outputs
Python      : 3.13.7
Pandas      : 2.3.2
PYENV_ENV   : (unset)
DATABASE_URL: set
PGHOST      : unset
PGDATABASE  : unset
PGUSER      : unset
PGPORT      : unset
Write test  : OK

Project layout (key paths):
  NHL-Beyond-27/
   ├─ data/
   │   └─ outputs/
   └─ logs/

## Download `peak_player_season_stats.csv` from S3 into `data/`

We fetch the already-prepared **peak player season stats** dataset from our S3 bucket.

**Auth notes**
- Set `AWS_PROFILE=nhl-beyond` (or your profile) in your shell or `.env`.
- Bucket name defaults from `S3_BUCKET_NAME` (falls back to our project bucket).

**Where it lands**
- `data/peak_player_season_stats.csv`

In [58]:
from pathlib import Path

import pandas as pd

csv_path = Path("data/peak_player_season_stats.csv")
assert csv_path.exists(), "Expected data/peak_player_season_stats.csv"
peak = pd.read_csv(csv_path)
peak.head(8)

,Player,EH_ID,API ID,Season,Team,Position,Shoots,Birthday,Age,Draft Yr,...,CA/60,xGF/60,xGA/60,G±/60,S±/60,F±/60,C±/60,xG±/60,Sh%,Sv%
0,A.J. Greer,A.J..GREER,8478421,22-23,BOS,L,L,1996-12-14,25,2015,...,49.64,2.69,2.07,0.93,-0.01,0.93,-1.96,0.63,8.82,94.71
1,A.J. Greer,A.J..GREER,8478421,23-24,CGY,L,L,1996-12-14,26,2015,...,61.74,2.23,2.59,-1.01,-4.33,-3.19,-6.37,-0.36,6.58,90.99
2,A.J. Greer,A.J..GREER,8478421,24-25,FLA,L,L,1996-12-14,27,2015,...,51.40,2.79,2.16,0.20,3.06,5.69,10.02,0.63,6.66,93.34
3,Aaron Ekblad,AARON.EKBLAD,8477932,21-22,FLA,D,R,1996-02-07,25,2014,...,47.74,3.29,2.30,1.61,11.76,16.77,21.58,0.99,9.74,91.95
4,Aaron Ekblad,AARON.EKBLAD,8477932,22-23,FLA,D,R,1996-02-07,26,2014,...,54.92,3.15,3.07,-0.38,4.71,5.26,10.62,0.08,7.52,90.15
5,Aaron Ekblad,AARON.EKBLAD,8477932,23-24,FLA,D,R,1996-02-07,27,2014,...,50.90,3.08,2.28,1.37,6.66,10.62,22.40,0.81,7.86,95.36
6,Aaron Ekblad,AARON.EKBLAD,8477932,24-25,FLA,D,R,1996-02-07,28,2014,...,55.16,2.82,2.54,0.60,6.92,9.95,14.79,0.29,7.76,92.47
7,Adam Erne,ADAM.ERNE,8477454,20-21,DET,L,L,1995-04-20,25,2013,...,57.54,2.02,2.43,-0.16,-3.29,-6.70,-10.38,-0.41,7.10,93.14

## Optional: Load `peak_player_season_stats.csv` into Postgres

You **do not need** this step if you’re restoring the database from our dump per the “Recreate DB” instructions.

Run this only if you want to (re)create the table directly from the CSV.

**Script:** `ingest_peak_season.py` → writes to table **public.player_peak_season**

**Prereqs**
- AWS auth (only needed if you use the script’s `--download-only`; we already have the file locally)
- DB auth: set `DATABASE_URL` in `.env` **or** the individual vars used by `db_utils.py`

**Modes & flags**
- `--mode upsert`  → merge rows by key (no truncate)
- `--mode replace` → truncate table, then load fresh
- `--download-only` → just download the CSV and **exit** (skip DB writes)

**Uniqueness key (for upsert)**
- `--conflict-key player_season_team` *(default)* : allows multiple rows per season when traded
- `--conflict-key player_season` : use only if you enforce one row per season per player

In [59]:
# Pick ONE of the commands below (uncomment what you want)

# 1) Download-only (skips DB load) — not required since we already read the CSV locally
# !python ingest_peak_season.py --download-only

# 2) Merge into DB (no truncate)
# !python ingest_peak_season.py --mode upsert --conflict-key player_season_team

# 3) Truncate + load fresh
# !python ingest_peak_season.py --mode replace --conflict-key player_season_team

In [60]:
# Quick DB sanity check (safe to skip if you didn’t load)
from db_utils import get_db_engine

try:
    engine = get_db_engine()
    df = pd.read_sql("SELECT COUNT(*) AS n FROM public.player_peak_season", engine)
    display(df)
    sample = pd.read_sql(
        'SELECT player, season, team, position, "CF%", "CF/60", "CA/60" '
        "FROM public.player_peak_season LIMIT 5",
        engine,
    )
    display(sample)
except Exception as e:
    print("Skipping DB check (engine not configured or table missing). Details:", e)

2025-09-29 23:56:06,904 - INFO - db_utils - Using DATABASE_URL from environment.

      n
0  3121

Skipping DB check (engine not configured or table missing). Details: sqlalchemy.cyextension.immutabledict.immutabledict is not a sequence

### Optional: export a small sample for non-DB readers

In [61]:
# # Write a small slice to CSV for quick inspection (no DB needed)
# (peak.head(100)).to_csv(OUT / "peak_player_sample_100.csv", index=False)
# OUT / "peak_player_sample_100.csv"

from pathlib import Path

import pandas as pd
from IPython.display import display

OUT = Path("data/outputs"); OUT.mkdir(parents=True, exist_ok=True)

out_path = OUT / "peak_player_sample_100.csv"
peak.head(100).to_csv(out_path, index=False)
print(f"Wrote: {out_path.resolve()}")

# show 8 rows
display(peak.head(8))          # or: print(peak.head(10).to_string(index=False))

Wrote: /Users/ericwiniecke/Documents/github/NHL-Beyond-27/data/outputs/peak_player_sample_100.csv

,Player,EH_ID,API ID,Season,Team,Position,Shoots,Birthday,Age,Draft Yr,...,CA/60,xGF/60,xGA/60,G±/60,S±/60,F±/60,C±/60,xG±/60,Sh%,Sv%
0,A.J. Greer,A.J..GREER,8478421,22-23,BOS,L,L,1996-12-14,25,2015,...,49.64,2.69,2.07,0.93,-0.01,0.93,-1.96,0.63,8.82,94.71
1,A.J. Greer,A.J..GREER,8478421,23-24,CGY,L,L,1996-12-14,26,2015,...,61.74,2.23,2.59,-1.01,-4.33,-3.19,-6.37,-0.36,6.58,90.99
2,A.J. Greer,A.J..GREER,8478421,24-25,FLA,L,L,1996-12-14,27,2015,...,51.40,2.79,2.16,0.20,3.06,5.69,10.02,0.63,6.66,93.34
3,Aaron Ekblad,AARON.EKBLAD,8477932,21-22,FLA,D,R,1996-02-07,25,2014,...,47.74,3.29,2.30,1.61,11.76,16.77,21.58,0.99,9.74,91.95
4,Aaron Ekblad,AARON.EKBLAD,8477932,22-23,FLA,D,R,1996-02-07,26,2014,...,54.92,3.15,3.07,-0.38,4.71,5.26,10.62,0.08,7.52,90.15
5,Aaron Ekblad,AARON.EKBLAD,8477932,23-24,FLA,D,R,1996-02-07,27,2014,...,50.90,3.08,2.28,1.37,6.66,10.62,22.40,0.81,7.86,95.36
6,Aaron Ekblad,AARON.EKBLAD,8477932,24-25,FLA,D,R,1996-02-07,28,2014,...,55.16,2.82,2.54,0.60,6.92,9.95,14.79,0.29,7.76,92.47
7,Adam Erne,ADAM.ERNE,8477454,20-21,DET,L,L,1995-04-20,25,2013,...,57.54,2.02,2.43,-0.16,-3.29,-6.70,-10.38,-0.41,7.10,93.14

## Build: player_five_year_aligned (five consecutive seasons, EV ≥ 500 min)

Script: `build_player_streaks_and_aligned.py`

**What it does**
- Finds **consecutive** 5-season streaks per player (seasons mapped to `rel_age ∈ {-2,-1,0,1,2}` where **0 = peak**).
- Applies minutes filter: **EV TOI ≥ 500 min** per season within the 5-year window.
- Produces a tidy table `public.player_five_year_aligned` with at least:
  - `player, position, peak_year, rel_age, start_year, season, age, cf_pct, cf60, ca60`
- Keys: conceptually `(player, peak_year, rel_age)` should be unique.

**CLI (typical)**
- `--mode upsert` → insert/update rows (no truncate)
- `--mode replace` → truncate then rebuild
- other options (if present): thresholds, seasons, schema

*We use the same database environment as earlier (see .env).*

In [62]:
# Run the builder (choose one) 
# !python build_player_streaks_and_aligned.py --mode upsert
# !python build_player_streaks_and_aligned.py --mode replace

In [63]:
# Sanity check
import pandas as pd
from db_utils import get_db_engine

engine = get_db_engine()
n = pd.read_sql("SELECT COUNT(*) AS n FROM public.player_five_year_aligned", engine)
display(n)

peek = pd.read_sql(
    "SELECT player, position, peak_year, rel_age, season, age, cf_pct, cf60, ca60 "
    "FROM public.player_five_year_aligned "
    "ORDER BY player, peak_year, rel_age LIMIT 10",
    engine,
)
display(peek)

2025-09-29 23:56:06,940 - INFO - db_utils - Using DATABASE_URL from environment.

      n
0  1410

,player,position,peak_year,rel_age,season,age,cf_pct,cf60,ca60
0,Adam Henrique,C,2017,-2,15-16,25,45.52,41.51,49.69
1,Adam Henrique,C,2017,-1,16-17,26,46.34,49.91,57.80
2,Adam Henrique,C,2017,0,17-18,27,50.29,57.90,57.23
3,Adam Henrique,C,2017,1,18-19,28,45.65,50.54,60.17
4,Adam Henrique,C,2017,2,19-20,29,51.12,57.97,55.42
5,Adam Larsson,D,2020,-2,18-19,25,49.44,54.54,55.77
6,Adam Larsson,D,2020,-1,19-20,26,47.34,50.69,56.39
7,Adam Larsson,D,2020,0,20-21,27,46.85,45.98,52.16
8,Adam Larsson,D,2020,1,21-22,28,49.51,51.12,52.13
9,Adam Larsson,D,2020,2,22-23,29,55.06,60.94,49.74

## Build: player_five_year_aligned_z (within-player z, spicy, curvature)

Script: `build_player_five_year_aligned_z.py`

**What it does**
- Casts `cf_pct`, `cf60`, `ca60` to numeric.
- Computes **within-player** z-scores: `cf_pct_z`, `cf60_z`, `ca60_z`.
- Shifts `peak_year → peak_year + 1` so it corresponds to the season end year (`YY-YY`).
- Computes:
  - `spicy_score` (equal-weight composite): `mean(cf_pct_z, cf60_z, -ca60_z)`
  - `spicy_weighted` (role-aware): heavier weight on possession for D, a bit more on cf60 for F.
  - curvature vs peak deltas: `_dz` columns like `cf60_dz = cf60_z - cf60_z_at_rel_age_0`.

**CLI**
- `--mode upsert` (idempotent), `--mode replace` (truncate+insert), and (if you kept it) `--mode recreate`.

In [64]:
# Export + preview: aligned and aligned_z (limit prints to 10 rows each)
from pathlib import Path

import pandas as pd
from db_utils import get_db_engine

OUT = Path("data/outputs"); OUT.mkdir(parents=True, exist_ok=True)
engine = get_db_engine()

# Write both CSVs
aligned_df   = pd.read_sql("SELECT * FROM public.player_five_year_aligned LIMIT 200", engine)
aligned_path = OUT / "aligned_sample_200.csv"
aligned_df.to_csv(aligned_path, index=False)

aligned_z_df   = pd.read_sql("SELECT * FROM public.player_five_year_aligned_z LIMIT 200", engine)
aligned_z_path = OUT / "aligned_z_sample_200.csv"
aligned_z_df.to_csv(aligned_z_path, index=False)

# Report + print only head(10) from each
print(f"Wrote: {aligned_path.resolve()}   shape={aligned_df.shape}")
with pd.option_context("display.max_columns", None, "display.width", 160):
    print("\npublic.player_five_year_aligned (head 10):")
    print(aligned_df.head(10).to_string(index=False))

print(f"\nWrote: {aligned_z_path.resolve()}   shape={aligned_z_df.shape}")
with pd.option_context("display.max_columns", None, "display.width", 160):
    print("\npublic.player_five_year_aligned_z (head 10):")
    print(aligned_z_df.head(10).to_string(index=False))

2025-09-29 23:56:06,965 - INFO - db_utils - Using DATABASE_URL from environment.

Wrote: /Users/ericwiniecke/Documents/github/NHL-Beyond-27/data/outputs/aligned_sample_200.csv   shape=(200, 11)

public.player_five_year_aligned (head 10):
     player  peak_year  rel_age  start_year season  age  cf_pct  cf60  ca60                       created_at position
 Torey Krug       2018       -2        2016  16-17   25   57.93 65.05 47.25 2025-09-15 21:29:49.353315+00:00        D
 Torey Krug       2018       -1        2017  17-18   26   54.36 62.34 52.33 2025-09-15 21:29:49.353315+00:00        D
 Torey Krug       2018        0        2018  18-19   27   54.13 60.50 51.27 2025-09-15 21:29:49.353315+00:00        D
 Torey Krug       2018        1        2019  19-20   28   56.09 62.59 48.99 2025-09-15 21:29:49.353315+00:00        D
 Torey Krug       2018        2        2020  20-21   29   47.80 50.21 54.84 2025-09-15 21:29:49.353315+00:00        D
Milan Lucic       2015       -2        2013  13-14   25   54.99 64.36 52.69 2025-09-15 21:29:49.353315+00:00        L
Milan Lucic       2015       -1        2014  14-15   26   51.37 58.32 55.20 2025-09-15 21:29:49.353315+00:00        L
Milan Lucic       2015        0        2015  15-16   27   59.88 68.74 46.05 2025-09-15 21:29:49.353315+00:00        L
Milan Lucic       2015        1        2016  16-17   28   51.79 57.88 53.88 2025-09-15 21:29:49.353315+00:00        L
Milan Lucic       2015        2        2017  17-18   29   50.42 60.66 59.66 2025-09-15 21:29:49.353315+00:00        L

Wrote: /Users/ericwiniecke/Documents/github/NHL-Beyond-27/data/outputs/aligned_z_sample_200.csv   shape=(200, 21)

public.player_five_year_aligned_z (head 10):
       player position  peak_year  rel_age  start_year season  age  cf_pct  cf60  ca60  cf_pct_z    cf60_z    ca60_z  spicy_score  spicy_weighted  cf_pct_dz   cf60_dz   ca60_dz  spicy_unw_dz  spicy_w_dz                       created_at
Adam Henrique        C       2018       -1        2016  16-17   26   46.34 49.91 57.80 -0.534689 -0.242816  0.440476    -0.405994       -0.428285  -1.462619 -1.171556  0.144460     -0.926212   -1.111668 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018        2        2019  19-20   29   51.12 57.97 55.42  1.235265  0.939005 -0.162708     0.778992        0.931875   0.307335  0.010264 -0.458724      0.258774    0.248492 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018       -2        2015  15-16   25   45.52 41.51 49.69 -0.838321 -1.474489 -1.614911    -0.232633       -0.538525  -1.766251 -2.403230 -1.910927     -0.752851   -1.221909 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018        0        2017  17-18   27   50.29 57.90 57.23  0.927930  0.928741  0.296016     0.520218        0.683384   0.000000  0.000000  0.000000      0.000000    0.000000 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018        1        2018  18-19   28   45.65 50.54 60.17 -0.790184 -0.150440  1.041126    -0.660584       -0.648449  -1.718114 -1.079181  0.745110     -1.180802   -1.331833 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021        0        2020  20-21   27   46.85 45.98 52.16 -0.855858 -1.203708 -0.387405    -0.557387       -0.552449   0.000000  0.000000  0.000000      0.000000    0.000000 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021        2        2022  22-23   29   55.06 60.94 49.74  1.662635  1.494444 -1.257089     1.471390        1.507333   2.518494  2.698152 -0.869684      2.028777    2.059783 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021        1        2021  21-22   28   49.51 51.12 52.13 -0.039879 -0.276669 -0.398186     0.027213        0.044183   0.815980  0.927039 -0.010781      0.584600    0.596632 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021       -2        2018  18-19   25   49.44 54.54 55.77 -0.061352  0.340155  0.909934    -0.210377       -0.235625   0.794507  1.543862  1.297339      0.347010    0.316824 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021       -1        2019  19-20   26   47.34 50.69 56.39 -0.705546 -0.354223  1.132746    -0.730838       -0.763441   0.150312  0.849485  1.520150     -0.173451   -0.210992 2025-09-28 22:06:35.402214+00:00

## Discussion: What these z-tables mean (short + exact)

**Within-player z-scores (5-year aligned window).**
For each player \(i\) and stat \(X \in \{\text{CF}\%,\ \text{CF}/60,\ \text{CA}/60\}\) over \(t \in \{-2,-1,0,1,2\}\) (peak at \(t=0\)):
\[
\bar X_i=\frac{1}{5}\sum_{t} X_{i,t},\qquad
s_i=\sqrt{\frac{1}{4}\sum_{t}\big(X_{i,t}-\bar X_i\big)^2},\qquad
z_{i,t}(X)=\frac{X_{i,t}-\bar X_i}{s_i}\ \ (\text{set }z=0\text{ if }s_i=0).
\]
This answers: *“How is this season versus this same player’s own 5-year norm?”*
(Using **CF/60** makes it a per-60 rate; the **minus on CA/60** reflects that lower is better.)

**Composites used in Book 1 (built from those within-player z’s).**
- **SPICY (equal-weight):**
\[
\text{SPICY}=\tfrac{1}{3}\,z(\text{CF}\%)\;+\;\tfrac{1}{3}\,z(\text{CF}/60)\;-\;\tfrac{1}{3}\,z(\text{CA}/60).
\]
- **Role-weighted (primary):**
  - **Forwards (F):**
  \[
  0.5\,z(\text{CF}\%)\;+\;0.3\,z(\text{CF}/60)\;-\;0.2\,z(\text{CA}/60).
  \]
  - **Defense (D):**
  \[
  0.3\,z(\text{CF}\%)\;+\;0.2\,z(\text{CF}/60)\;-\;0.5\,z(\text{CA}/60).
  \]

**Curvature vs peak & Peak Δ.**
- **Curvature** (per stat or composite): \(\Delta z_{i,t}=z_{i,t}-z_{i,0}\) (deviation from peak year).
- **Peak Δ (headline delta):**
\[
\Delta^{\text{peak}}_i = z_{i,0} - \frac{1}{5}\sum_{t\in\{-2,-1,0,1,2\}} z_{i,t}
\]
*(Optionally exclude \(t=0\): subtract the mean of \(\{-2,-1,1,2\}\) instead.)*

**Interpretation.**
- \(z>0\): season above the player’s own baseline; \(z<0\): below.
- The role-weighted composite turns three standardized signals into one, tailored for F vs D.
- Larger **Peak Δ** means the player’s peak sits further above their typical 5-year level.

> **Teaser — Peak Δ:** In Book 3 we’ll quantify how far a player’s **peak season** sits above their own 5-year norm (Peak Δ). For now, just know that bigger is better; details and full results come later.

In [65]:
# Ensure dfz is usable for the teaser, then plot top-5 Peak Δ
import numpy as np
import pandas as pd
import plotly.graph_objects as go


def ensure_dfz_ready(dfz):
    dfz = dfz.copy()
    # rel_age numeric + standard window
    dfz["rel_age"] = pd.to_numeric(dfz["rel_age"], errors="coerce").astype("Int64")
    # role normalization (if missing, try to infer from 'position')
    if "role" not in dfz.columns and "position" in dfz.columns:
        dfz["role"] = dfz["position"].astype(str).str.upper().map(lambda x: "D" if x.startswith("D") else "F")
    # choose composite Δz column
    col = "spicy_w_dz" if "spicy_w_dz" in dfz.columns else (
          "spicy_weighted_dz" if "spicy_weighted_dz" in dfz.columns else None)
    if col is None:
        raise KeyError("Need Δz composite column like 'spicy_w_dz' in dfz.")
    # restrict window
    win = dfz[dfz["rel_age"].isin([-2,-1,0,1,2]) & dfz["role"].isin(["F","D"])]
    if win.empty:
        raise ValueError("No rows in the 5-year window with roles F/D.")
    need = {"player","role","rel_age",col}
    missing = need - set(win.columns)
    if missing:
        raise KeyError(f"Missing columns: {missing}")
    return win, col

def peak_delta_teaser(dfz, k=5):
    win, col = ensure_dfz_ready(dfz)
    delta = (win.groupby(["player","role"])[col].mean().mul(-1)
               .rename("peak_delta").reset_index())
    if delta.empty:
        raise ValueError("Could not compute Peak Δ (no grouped rows).")
    topk = delta.nlargest(min(k, len(delta)), "peak_delta")

    palette = {"D":"#1f77b4","F":"#ff7f0e"}
    fig = go.Figure(go.Bar(
        x=topk["peak_delta"],
        y=topk["player"],
        orientation="h",
        marker_color=[palette.get(r,"#888") for r in topk["role"]],
        hovertemplate="<b>%{y}</b><br>Peak Δ: %{x:.2f}<br>Role: %{customdata}",
        customdata=topk["role"],
    ))
    fig.update_layout(
        title="Peak Δ teaser (Top 5) — higher = bigger lift vs own norm",
        xaxis_title="Peak Δ (role-weighted Δz)",
        yaxis_title="",
        template="plotly_white",
        height=280, margin=dict(l=120, r=10, t=50, b=30), showlegend=False,
    )
    fig.update_yaxes(autorange="reversed")
    xvals = topk["peak_delta"].to_numpy()
    span = float(np.max(xvals) - np.min(xvals)) if len(xvals) else 0.0
    fig.update_xaxes(tickformat=".2f", dtick=0.05 if span < 0.6 else 0.1)
    return fig

# Run the teaser
peak_delta_teaser(dfz, k=5).show()

### SPICY and SPICY (role-weighted)

**What is SPICY?**  
A composite built from *within-player* z-scores of three even-strength possession stats—CF%, CF/60 (higher is better), and CA/60 (lower is better)—over the 5-year aligned window. It puts the three signals on the same scale and rolls them into one number.

**Equal-weight SPICY (baseline):**  
\[
\text{SPICY}=\tfrac{1}{3}\,z(\text{CF}\%)\;+\;\tfrac{1}{3}\,z(\text{CF}/60)\;-\;\tfrac{1}{3}\,z(\text{CA}/60)
\]
- Interpret: \(z>0\) = above the player’s own 5-year norm; \(z<0\) = below.

**Role-weighted SPICY (primary in Book 1):**  
Weights reflect different responsibilities for Forwards (F) vs Defense (D).
- **Forwards (F):** \(\;0.5\,z(\text{CF}\%) + 0.3\,z(\text{CF}/60) - 0.2\,z(\text{CA}/60)\)
- **Defense (D):**  \(\;0.3\,z(\text{CF}\%) + 0.2\,z(\text{CF}/60) - 0.5\,z(\text{CA}/60)\)

**Why role weights?**  
They emphasize puck possession for D and on-puck shot creation for F, yielding a single score that’s comparable within role while still grounded in each player’s own baseline.

**How to read it.**  
- Higher SPICY/role-weighted SPICY ⇒ stronger season relative to that player’s typical level.  
- Negative values signal below-baseline years; near-zero ≈ “typical” season.

In [66]:
# SPICY teaser — mean composite (Δz) by relative age, robust to missing 'role'
import numpy as np
import pandas as pd
import plotly.graph_objects as go


def spicy_teaser(dfz):
    d = dfz.copy()

    # Choose composite column (you said you have only *_dz columns)
    col = "spicy_w_dz" if "spicy_w_dz" in d.columns else (
          "spicy_weighted_dz" if "spicy_weighted_dz" in d.columns else None)
    if col is None:
        raise KeyError("Need a Δz composite column like 'spicy_w_dz' in dfz.")

    # Ensure role exists (infer from position if needed)
    if "role" not in d.columns:
        if "position" in d.columns:
            d["role"] = d["position"].astype(str).str.upper().map(lambda x: "D" if x.startswith("D") else "F")
        else:
            # last-resort fallback so the plot still renders
            d["role"] = "F"

    # rel_age numeric + filter to the 5-year window
    d["rel_age"] = pd.to_numeric(d["rel_age"], errors="coerce")
    d = d[d["rel_age"].isin([-2, -1, 0, 1, 2])]

    # Aggregate mean ± 95% CI of Δz by role, rel_age
    g = (d.groupby(["role", "rel_age"])
           .agg(n=(col, "size"), mean=(col, "mean"), sd=(col, "std"))
           .reset_index())
    g["se"] = g["sd"].fillna(0) / np.sqrt(g["n"].clip(lower=1))
    g["lower"] = g["mean"] - 1.96*g["se"]
    g["upper"] = g["mean"] + 1.96*g["se"]

    # Plot (lines only, no ribbons)
    palette = {"D": "#1f77b4", "F": "#ff7f0e"}
    fig = go.Figure()
    for role in g["role"].dropna().unique():
        sub = g[g["role"] == role].sort_values("rel_age")
        if sub.empty:
            continue
        fig.add_trace(go.Scatter(
            x=sub["rel_age"],
            y=sub["mean"],
            mode="lines+markers",
            line=dict(color=palette.get(role, "#888"), width=2),
            marker=dict(size=7),
            name=f"{role} mean Δz",
            hovertemplate="rel_age=%{x}<br>mean Δz=%{y:.2f}<br>n=%{customdata}",
            customdata=sub["n"],
        ))

    # Tight y-range
    lo = float(np.nanmin(g["lower"])) if np.isfinite(np.nanmin(g["lower"])) else float(np.nanmin(g["mean"]))
    hi = float(np.nanmax(g["upper"])) if np.isfinite(np.nanmax(g["upper"])) else float(np.nanmax(g["mean"]))
    pad = max((hi - lo)*0.05, 0.02)

    fig.update_layout(
        title="SPICY Δz (role-weighted) — mean by rel_age (teaser)",
        xaxis_title="rel_age (−2 … 2, peak at 0)",
        yaxis_title="Δz from peak (role-weighted)",
        template="plotly_white",
        legend=dict(title=""),
        height=360,
        margin=dict(l=60, r=10, t=50, b=40),
    )
    fig.update_xaxes(tickvals=[-2, -1, 0, 1, 2])
    fig.update_yaxes(range=[lo - pad, hi + pad], dtick=0.05, tickformat=".2f", zeroline=True)
    return fig

spicy_teaser(dfz).show()

### Troubleshooting

**Database**
- **DATABASE_URL missing**: add to `.env` (or individual vars `DATABASE_TYPE, DBAPI, ENDPOINT, USER, PASSWORD, PORT, DATABASE`).  
  Example: `DATABASE_URL=postgresql+psycopg2://user:pass@localhost:5432/nhl`.
- **psycopg2 not found**: `pip install psycopg2-binary`.
- **Permission denied**: ensure your DB role can `CREATE TABLE`, `CREATE VIEW`, and `CREATE INDEX` in `public`.
- **SSL / connection errors**: if using a managed DB, match its SSL settings (you may need `?sslmode=require` in the URL).

**AWS / S3**
- **No credentials**: set `AWS_PROFILE=nhl-beyond` (or run `aws configure --profile nhl-beyond`).
- **AccessDenied**: verify bucket name in `.env` (`S3_BUCKET_NAME`) and IAM permissions.

**.env warnings**
- `python-dotenv could not parse statement at line 1`: your `.env` has a stray character, unmatched quote, or a comment without `#`. Keep one `KEY=VALUE` per line.

**Paths**
- Expected EH export at `data/peak_player_season_stats.csv`. If not present, run `ingest_peak_season.py --download-only` first.

**Pre-commit hooks**
- In a rush, you can bypass hooks: `git commit -m "msg" --no-verify`. Come back later and run `pre-commit run -a` to clean up.

### Data Dictionary (selected fields)

**public.player_peak_season** (from Evolving-Hockey export)
- `player` (text) – player name.
- `eh_id` (text), `api_id` (bigint) – EH identifiers.
- `season` (text, `YY-YY`) – e.g., `20-21`.
- `team` (text), `position` (text).
- `age` (int), `games_played` (int).
- Shot/possession metrics: `"CF%"`, `"CF/60"`, `"CA/60"`, `"xGF%"`, etc.  
  *(Exact cases preserved from the CSV; quotes required in SQL.)*

**public.player_five_year_aligned** (derived)
- `player`, `position`.
- `peak_year` (int) – **end** year of peak season (e.g., `2021` for `20-21`).
- `rel_age` (int) – `-2,-1,0,1,2` relative to the peak season.
- `start_year` (int), `season` (text), `age` (int).
- `cf_pct` (numeric), `cf60` (numeric), `ca60` (numeric).

**public.player_five_year_aligned_z** (within-player standardization)
- (All keys above) +
- `cf_pct_z`, `cf60_z`, `ca60_z` – z-scores **within the same player** across their 5-year window.
- `spicy_score` – equal-weight composite: mean of `(cf_pct_z, cf60_z, -ca60_z)` when available.
- `spicy_weighted` – role-aware fixed weights (D: more weight to CF%, larger penalty to CA60; F: slightly more CF60).
- Curvature vs peak (value at `rel_age=k` minus value at `rel_age=0`):  
  `cf_pct_dz`, `cf60_dz`, `ca60_dz`, `spicy_unw_dz`, `spicy_w_dz`.

**How to run (recap)**
1. Place EH export CSVs in `data/` (or run your existing scripts that generate outputs).
2. Ensure `data/outputs/player_five_year_aligned.csv` and `player_five_year_aligned_z.csv` are present.
3. Run the notebook top-to-bottom (it reads CSVs only, no DB needed).
4. Skim the previews, the SPICY/Δz teaser charts, and you’re done.

**Utility cell 1 — print the top 60 installed packages (name==sorted, harmless)**

In [67]:
# Top 60 packages (installed) — harmless environment snapshot
import json
import subprocess
import sys

try:
    proc = subprocess.run(
        [sys.executable, "-m", "pip", "list", "--format", "json"],
        capture_output=True, text=True, check=True
    )
    pkgs = json.loads(proc.stdout)
    pkgs_sorted = sorted(pkgs, key=lambda d: d.get("name","").lower())[:60]
    print(f"Top {len(pkgs_sorted)} packages (alphabetical):")
    for p in pkgs_sorted:
        print(f"  {p['name']}=={p['version']}")
except Exception as e:
    print("Could not list packages:", e)

Top 60 packages (alphabetical):
  appnope==0.1.4
  asttokens==3.0.0
  attrs==25.3.0
  beautifulsoup4==4.13.5
  black==25.1.0
  boto3==1.40.25
  botocore==1.40.25
  bs4==0.0.2
  certifi==2025.8.3
  cfgv==3.4.0
  charset-normalizer==3.4.3
  choreographer==1.1.1
  click==8.2.1
  comm==0.2.3
  debugpy==1.8.17
  decorator==5.2.1
  distlib==0.4.0
  dotenv==0.9.9
  executing==2.2.1
  fastjsonschema==2.21.2
  filelock==3.19.1
  h11==0.16.0
  identify==2.6.14
  idna==3.10
  iniconfig==2.1.0
  ipykernel==6.30.1
  ipython==9.5.0
  ipython_pygments_lexers==1.1.1
  jedi==0.19.2
  jmespath==1.0.1
  jsonschema==4.25.1
  jsonschema-specifications==2025.9.1
  jupyter_client==8.6.3
  jupyter_core==5.8.1
  kaleido==1.1.0
  logistro==1.1.0
  lxml==6.0.1
  matplotlib-inline==0.1.7
  mypy_extensions==1.1.0
  narwhals==2.5.0
  nbformat==5.10.4
  nest-asyncio==1.6.0
  nhl-beyond27==0.1.0
  nodeenv==1.9.1
  numpy==2.3.2
  orjson==3.11.3
  outcome==1.3.0.post0
  packaging==25.0
  pandas==2.3.2
  parso==0.8.5
  pathspec==0.12.1
  patsy==1.0.1
  pexpect==4.9.0
  pip==25.2
  platformdirs==4.4.0
  plotly==6.3.0
  pluggy==1.6.0
  pre_commit==4.3.0
  prompt_toolkit==3.0.52
  psutil==7.1.0

**Utility cell 2 — copy the aligned-z table into outputs (and show a tiny preview)**

In [68]:
import shutil
from datetime import datetime
from pathlib import Path

import pandas as pd

OUT = Path("data/outputs"); OUT.mkdir(parents=True, exist_ok=True)
src = OUT / "player_five_year_aligned_z.csv"
dst = OUT / f"player_five_year_aligned_z_copy_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"

assert src.exists(), f"Missing source CSV: {src}"
shutil.copy2(src, dst)
print("Copied:", dst.resolve())

dfz = pd.read_csv(src)
with pd.option_context("display.max_columns", None, "display.width", 160):
    print("\nplayer_five_year_aligned_z (head 10):")
    print(dfz.head(10).to_string(index=False))

Copied: /Users/ericwiniecke/Documents/github/NHL-Beyond-27/data/outputs/player_five_year_aligned_z_copy_20250929_235607.csv

player_five_year_aligned_z (head 10):
       player position  peak_year  rel_age  start_year season  age  cf_pct  cf60  ca60  cf_pct_z    cf60_z    ca60_z  spicy_score  spicy_weighted  cf_pct_dz   cf60_dz   ca60_dz  spicy_unw_dz  spicy_w_dz                       created_at
Adam Henrique        C       2018       -1        2016  16-17   26   46.34 49.91 57.80 -0.534689 -0.242816  0.440476    -0.405994       -0.428285  -1.462619 -1.171556  0.144460     -0.926212   -1.111668 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018        2        2019  19-20   29   51.12 57.97 55.42  1.235265  0.939005 -0.162708     0.778992        0.931875   0.307335  0.010264 -0.458724      0.258774    0.248492 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018       -2        2015  15-16   25   45.52 41.51 49.69 -0.838321 -1.474489 -1.614911    -0.232633       -0.538525  -1.766251 -2.403230 -1.910927     -0.752851   -1.221909 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018        0        2017  17-18   27   50.29 57.90 57.23  0.927930  0.928741  0.296016     0.520218        0.683384   0.000000  0.000000  0.000000      0.000000    0.000000 2025-09-28 22:06:35.402214+00:00
Adam Henrique        C       2018        1        2018  18-19   28   45.65 50.54 60.17 -0.790184 -0.150440  1.041126    -0.660584       -0.648449  -1.718114 -1.079181  0.745110     -1.180802   -1.331833 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021        0        2020  20-21   27   46.85 45.98 52.16 -0.855858 -1.203708 -0.387405    -0.557387       -0.552449   0.000000  0.000000  0.000000      0.000000    0.000000 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021        2        2022  22-23   29   55.06 60.94 49.74  1.662635  1.494444 -1.257089     1.471390        1.507333   2.518494  2.698152 -0.869684      2.028777    2.059783 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021        1        2021  21-22   28   49.51 51.12 52.13 -0.039879 -0.276669 -0.398186     0.027213        0.044183   0.815980  0.927039 -0.010781      0.584600    0.596632 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021       -2        2018  18-19   25   49.44 54.54 55.77 -0.061352  0.340155  0.909934    -0.210377       -0.235625   0.794507  1.543862  1.297339      0.347010    0.316824 2025-09-28 22:06:35.402214+00:00
 Adam Larsson        D       2021       -1        2019  19-20   26   47.34 50.69 56.39 -0.705546 -0.354223  1.132746    -0.730838       -0.763441   0.150312  0.849485  1.520150     -0.173451   -0.210992 2025-09-28 22:06:35.402214+00:00